FROM wazopbx/wazo-dird

ADD . /usr/src/wazo-microsoft

ENV PYTHONDONTWRITEBYTECODE='true'

RUN true \
    && cd /usr/src/wazo-microsoft \
    && pip install -r requirements.txt \
    && python setup.py develop \
    && true
