debian_depends:
  - python3-flask
  - python3-marshmallow
  - python3-requests
  - python3-requests-oauthlib
  - wazo-auth
  - wazo-auth-client-python3
  - wazo-dird
  - xivo-lib-python-python3
description: Add microsoft as an external authentication and directory resources
display_name: Microsoft integration
homepage: https://github.com/tinxhq/wazo-microsoft
author: Wazo Team
name: wazo-microsoft
namespace: official
plugin_format_version: 1
version: 2.0.2-1
tags:
  - authentication
  - contacts
min_wazo_version: 19.08
