name: wazo-microsoft
namespace: official
version: 1.0.0-1
description: Add microsoft as an external authentication resource
plugin_format_version: 1
debian_depends:
  - python3-requests-oauthlib
homepage: http://wazo.io
