debian_depends:
  - python3-requests-oauthlib
description: Add microsoft as an external authentication resource
display_name: Microsoft authentication
homepage: https://github.com/tinxhq/wazo-microsoft
author: Wazo Team
name: wazo-microsoft
namespace: official
plugin_format_version: 1
version: 1.0.0-1
tags:
  - authentication
