version: '3.7'
services:
  sync:
    depends_on:
      - auth
      - oauth2sync
      - postgres
      - rabbitmq
    environment:
      TARGETS: "auth:9497 oauth2sync:80 postgres:5432 rabbitmq:5672"
