version: '3.7'

services:

  auth:
    image: wazo-auth-microsoft-test
    environment:
      OAUTHLIB_INSECURE_TRANSPORT: 1
      XIVO_UUID: the-predefined-xivo-uuid
    ports:
      - "9497"
    volumes:
      - "../..:/usr/src/wazo-microsoft"
      - "./etc/wazo-auth/conf.d/default.yml:/etc/wazo-auth/conf.d/default.yml"
      - "./etc/wazo-auth/conf.d/microsoft.yml:/etc/wazo-auth/conf.d/microsoft.yml"
    command: "wazo-auth"

  auth-mock:
    image: "wazopbx/wazo-auth-mock"
    ports:
      - "9497"
    volumes:
      - "./ssl:/usr/local/share/ssl"

  dird:
    image: wazo-dird-microsoft-test
    environment:
      XIVO_UUID: the-predefined-xivo-uuid
    ports:
    - "9489"
    volumes:
    - "./etc/wazo-dird/conf.d/office365.yml:/etc/wazo-dird/conf.d/office365.yml"
    - "./etc/wazo-dird/conf.d/default.yml:/etc/wazo-dird/conf.d/default.yml"

  microsoft-mock:
    environment:
      FLASK_ENV: development
    image: microsoft-mock
    ports:
      - "80"

  oauth2sync:
    image: oauth2-synchronization-service
    ports:
      - "80"

  postgres-auth:
    image: wazopbx/wazo-auth-db
    ports:
      - "5432"

  postgres-dird:
    image: wazopbx/wazo-dird-db
    ports:
      - "5432"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
    volumes:
      - type: tmpfs
        target: /var/lib/rabbitmq

  swagger-validator:
    image: swaggerapi/swagger-validator
    ports:
      - "8080"

  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
